# Generated by Django 3.2.13 on 2022-10-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='movie_name',
            field=models.CharField(max_length=50),
        ),
    ]
